<?php

/**
 * v1_billing_promotionCode_create
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Request\billing;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayPromotionCodeCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayPromotionCodeCreateRequest   extends AlipayRequest  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayPromotionCodeCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'promotionCodeRequestId' => 'string',
        'couponId' => 'string',
        'code' => 'string',
        'expiryTime' => 'string',
        'minAmount' => '\request\model\PromotionCodeCreateMinAmount',
        'oneTimeOnly' => 'bool',
        'customerId' => 'string',
        'metadata' => 'string',
        'maxRedemptions' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'promotionCodeRequestId' => null,
        'couponId' => null,
        'code' => null,
        'expiryTime' => null,
        'minAmount' => null,
        'oneTimeOnly' => null,
        'customerId' => null,
        'metadata' => null,
        'maxRedemptions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'promotionCodeRequestId' => false,
        'couponId' => false,
        'code' => false,
        'expiryTime' => false,
        'minAmount' => false,
        'oneTimeOnly' => false,
        'customerId' => false,
        'metadata' => false,
        'maxRedemptions' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'promotionCodeRequestId' => 'promotionCodeRequestId',
        'couponId' => 'couponId',
        'code' => 'code',
        'expiryTime' => 'expiryTime',
        'minAmount' => 'minAmount',
        'oneTimeOnly' => 'oneTimeOnly',
        'customerId' => 'customerId',
        'metadata' => 'metadata',
        'maxRedemptions' => 'maxRedemptions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'promotionCodeRequestId' => 'setPromotionCodeRequestId',
        'couponId' => 'setCouponId',
        'code' => 'setCode',
        'expiryTime' => 'setExpiryTime',
        'minAmount' => 'setMinAmount',
        'oneTimeOnly' => 'setOneTimeOnly',
        'customerId' => 'setCustomerId',
        'metadata' => 'setMetadata',
        'maxRedemptions' => 'setMaxRedemptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'promotionCodeRequestId' => 'getPromotionCodeRequestId',
        'couponId' => 'getCouponId',
        'code' => 'getCode',
        'expiryTime' => 'getExpiryTime',
        'minAmount' => 'getMinAmount',
        'oneTimeOnly' => 'getOneTimeOnly',
        'customerId' => 'getCustomerId',
        'metadata' => 'getMetadata',
        'maxRedemptions' => 'getMaxRedemptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('promotionCodeRequestId', $data ?? [], null);
        $this->setIfExists('couponId', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('expiryTime', $data ?? [], null);
        $this->setIfExists('minAmount', $data ?? [], null);
        $this->setIfExists('oneTimeOnly', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('maxRedemptions', $data ?? [], null);

         $this->setPath("/ams/api/v1/billing/promotionCode/create"); 
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['promotionCodeRequestId'] === null) {
            $invalidProperties[] = "'promotionCodeRequestId' can't be null";
        }
        if ($this->container['couponId'] === null) {
            $invalidProperties[] = "'couponId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets promotionCodeRequestId
     *
     * @return string
     */
    public function getPromotionCodeRequestId()
    {
        return $this->container['promotionCodeRequestId'];
    }

    /**
     * Sets promotionCodeRequestId
     *
     * @param string $promotionCodeRequestId Merchant-supplied idempotency key for this create request. Must be unique per merchant. Cannot be empty. Maximum length: 64 characters. Idempotent replay: if a request is repeated with the same `promotionCodeRequestId` and the same parameters, the API returns `SUCCESS` together with the previously created promotion code. Replaying the same `promotionCodeRequestId` with different parameters returns `PARAM_ILLEGAL`.
     *
     * @return self
     */
    public function setPromotionCodeRequestId($promotionCodeRequestId)
    {
        $this->container['promotionCodeRequestId'] = $promotionCodeRequestId;

        return $this;
    }

    /**
     * Gets couponId
     *
     * @return string
     */
    public function getCouponId()
    {
        return $this->container['couponId'];
    }

    /**
     * Sets couponId
     *
     * @param string $couponId ID of the parent coupon this promotion code is associated with. The coupon must exist and be ACTIVE. Cannot be empty. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setCouponId($couponId)
    {
        $this->container['couponId'] = $couponId;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The customer-facing promotion code string (e.g. `SUMMER20`). Must be unique per merchant. Allowed characters for merchant-supplied codes: uppercase letters (A-Z), digits (0-9), hyphens (-), and underscores (_). If not provided, the server auto-generates a 12-character readable code (uppercase letters + digits; ambiguous characters O/0/I/1/L removed; uniqueness guaranteed with up to 5 retry attempts). If the supplied code collides with an existing code of the merchant, `PROMOTION_CODE_DUPLICATED` is returned. Maximum length: 128 characters.
     *
     * @return self
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets expiryTime
     *
     * @return string|null
     */
    public function getExpiryTime()
    {
        return $this->container['expiryTime'];
    }

    /**
     * Sets expiryTime
     *
     * @param string|null $expiryTime UTC timestamp (ISO 8601) after which the promotion code can no longer be redeemed. Must be a future time; a past value returns `PARAM_ILLEGAL`. If not set, the code has no independent expiry (subject to parent coupon's `redeemBy`).
     *
     * @return self
     */
    public function setExpiryTime($expiryTime)
    {
        $this->container['expiryTime'] = $expiryTime;

        return $this;
    }

    /**
     * Gets minAmount
     *
     * @return \model\PromotionCodeCreateMinAmount|null
     */
    public function getMinAmount()
    {
        return $this->container['minAmount'];
    }

    /**
     * Sets minAmount
     *
     * @param \model\PromotionCodeCreateMinAmount|null $minAmount minAmount
     *
     * @return self
     */
    public function setMinAmount($minAmount)
    {
        $this->container['minAmount'] = $minAmount;

        return $this;
    }

    /**
     * Gets oneTimeOnly
     *
     * @return bool|null
     */
    public function getOneTimeOnly()
    {
        return $this->container['oneTimeOnly'];
    }

    /**
     * Sets oneTimeOnly
     *
     * @param bool|null $oneTimeOnly If `true`, each customer can only redeem this promotion code once. Default: `false`.
     *
     * @return self
     */
    public function setOneTimeOnly($oneTimeOnly)
    {
        $this->container['oneTimeOnly'] = $oneTimeOnly;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId If set, restricts this promotion code to a specific customer. Must be a valid `customerId` in the system. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return string|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param string|null $metadata Merchant-defined key-value pairs stored as JSON string. Enforced constraints: max 50 keys; each key max 40 characters; each value max 500 characters. Requests exceeding these limits return `PARAM_ILLEGAL`. The value must be a valid JSON object string.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets maxRedemptions
     *
     * @return int|null
     */
    public function getMaxRedemptions()
    {
        return $this->container['maxRedemptions'];
    }

    /**
     * Sets maxRedemptions
     *
     * @param int|null $maxRedemptions Maximum number of times this promotion code can be redeemed. If not set or 0, redemptions are unlimited. Value range: 0-999999.
     *
     * @return self
     */
    public function setMaxRedemptions($maxRedemptions)
    {
        $this->container['maxRedemptions'] = $maxRedemptions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
