<?php

/**
 * v1_billing_customer_create
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Request\billing;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayCustomerCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayCustomerCreateRequest   extends AlipayRequest  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayCustomerCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'customerRequestId' => 'string',
        'referenceCustomerId' => 'string',
        'alipayUserId' => 'string',
        'email' => 'string',
        'firstName' => 'string',
        'lastName' => 'string',
        'mobileNo' => 'string',
        'country' => 'string',
        'state' => 'string',
        'city' => 'string',
        'address' => 'string',
        'addressDetail' => 'string',
        'zipcode' => 'string',
        'shippingName' => 'string',
        'shippingPhone' => 'string',
        'shippingCountry' => 'string',
        'shippingState' => 'string',
        'shippingCity' => 'string',
        'shippingAddress' => 'string',
        'shippingAddressDetail' => 'string',
        'shippingZipcode' => 'string',
        'description' => 'string',
        'currency' => 'string',
        'preferredLocales' => 'string',
        'defaultPaymentMethod' => 'string',
        'metadata' => 'array<string,string>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'customerRequestId' => null,
        'referenceCustomerId' => null,
        'alipayUserId' => null,
        'email' => null,
        'firstName' => null,
        'lastName' => null,
        'mobileNo' => null,
        'country' => null,
        'state' => null,
        'city' => null,
        'address' => null,
        'addressDetail' => null,
        'zipcode' => null,
        'shippingName' => null,
        'shippingPhone' => null,
        'shippingCountry' => null,
        'shippingState' => null,
        'shippingCity' => null,
        'shippingAddress' => null,
        'shippingAddressDetail' => null,
        'shippingZipcode' => null,
        'description' => null,
        'currency' => null,
        'preferredLocales' => null,
        'defaultPaymentMethod' => null,
        'metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'customerRequestId' => false,
        'referenceCustomerId' => false,
        'alipayUserId' => false,
        'email' => false,
        'firstName' => false,
        'lastName' => false,
        'mobileNo' => false,
        'country' => false,
        'state' => false,
        'city' => false,
        'address' => false,
        'addressDetail' => false,
        'zipcode' => false,
        'shippingName' => false,
        'shippingPhone' => false,
        'shippingCountry' => false,
        'shippingState' => false,
        'shippingCity' => false,
        'shippingAddress' => false,
        'shippingAddressDetail' => false,
        'shippingZipcode' => false,
        'description' => false,
        'currency' => false,
        'preferredLocales' => false,
        'defaultPaymentMethod' => false,
        'metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customerRequestId' => 'customerRequestId',
        'referenceCustomerId' => 'referenceCustomerId',
        'alipayUserId' => 'alipayUserId',
        'email' => 'email',
        'firstName' => 'firstName',
        'lastName' => 'lastName',
        'mobileNo' => 'mobileNo',
        'country' => 'country',
        'state' => 'state',
        'city' => 'city',
        'address' => 'address',
        'addressDetail' => 'addressDetail',
        'zipcode' => 'zipcode',
        'shippingName' => 'shippingName',
        'shippingPhone' => 'shippingPhone',
        'shippingCountry' => 'shippingCountry',
        'shippingState' => 'shippingState',
        'shippingCity' => 'shippingCity',
        'shippingAddress' => 'shippingAddress',
        'shippingAddressDetail' => 'shippingAddressDetail',
        'shippingZipcode' => 'shippingZipcode',
        'description' => 'description',
        'currency' => 'currency',
        'preferredLocales' => 'preferredLocales',
        'defaultPaymentMethod' => 'defaultPaymentMethod',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customerRequestId' => 'setCustomerRequestId',
        'referenceCustomerId' => 'setReferenceCustomerId',
        'alipayUserId' => 'setAlipayUserId',
        'email' => 'setEmail',
        'firstName' => 'setFirstName',
        'lastName' => 'setLastName',
        'mobileNo' => 'setMobileNo',
        'country' => 'setCountry',
        'state' => 'setState',
        'city' => 'setCity',
        'address' => 'setAddress',
        'addressDetail' => 'setAddressDetail',
        'zipcode' => 'setZipcode',
        'shippingName' => 'setShippingName',
        'shippingPhone' => 'setShippingPhone',
        'shippingCountry' => 'setShippingCountry',
        'shippingState' => 'setShippingState',
        'shippingCity' => 'setShippingCity',
        'shippingAddress' => 'setShippingAddress',
        'shippingAddressDetail' => 'setShippingAddressDetail',
        'shippingZipcode' => 'setShippingZipcode',
        'description' => 'setDescription',
        'currency' => 'setCurrency',
        'preferredLocales' => 'setPreferredLocales',
        'defaultPaymentMethod' => 'setDefaultPaymentMethod',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customerRequestId' => 'getCustomerRequestId',
        'referenceCustomerId' => 'getReferenceCustomerId',
        'alipayUserId' => 'getAlipayUserId',
        'email' => 'getEmail',
        'firstName' => 'getFirstName',
        'lastName' => 'getLastName',
        'mobileNo' => 'getMobileNo',
        'country' => 'getCountry',
        'state' => 'getState',
        'city' => 'getCity',
        'address' => 'getAddress',
        'addressDetail' => 'getAddressDetail',
        'zipcode' => 'getZipcode',
        'shippingName' => 'getShippingName',
        'shippingPhone' => 'getShippingPhone',
        'shippingCountry' => 'getShippingCountry',
        'shippingState' => 'getShippingState',
        'shippingCity' => 'getShippingCity',
        'shippingAddress' => 'getShippingAddress',
        'shippingAddressDetail' => 'getShippingAddressDetail',
        'shippingZipcode' => 'getShippingZipcode',
        'description' => 'getDescription',
        'currency' => 'getCurrency',
        'preferredLocales' => 'getPreferredLocales',
        'defaultPaymentMethod' => 'getDefaultPaymentMethod',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('customerRequestId', $data ?? [], null);
        $this->setIfExists('referenceCustomerId', $data ?? [], null);
        $this->setIfExists('alipayUserId', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('mobileNo', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('addressDetail', $data ?? [], null);
        $this->setIfExists('zipcode', $data ?? [], null);
        $this->setIfExists('shippingName', $data ?? [], null);
        $this->setIfExists('shippingPhone', $data ?? [], null);
        $this->setIfExists('shippingCountry', $data ?? [], null);
        $this->setIfExists('shippingState', $data ?? [], null);
        $this->setIfExists('shippingCity', $data ?? [], null);
        $this->setIfExists('shippingAddress', $data ?? [], null);
        $this->setIfExists('shippingAddressDetail', $data ?? [], null);
        $this->setIfExists('shippingZipcode', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('preferredLocales', $data ?? [], null);
        $this->setIfExists('defaultPaymentMethod', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);

         $this->setPath("/ams/api/v1/billing/customer/create"); 
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['customerRequestId'] === null) {
            $invalidProperties[] = "'customerRequestId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customerRequestId
     *
     * @return string
     */
    public function getCustomerRequestId()
    {
        return $this->container['customerRequestId'];
    }

    /**
     * Sets customerRequestId
     *
     * @param string $customerRequestId The unique ID assigned by a merchant to identify a request. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setCustomerRequestId($customerRequestId)
    {
        $this->container['customerRequestId'] = $customerRequestId;

        return $this;
    }

    /**
     * Gets referenceCustomerId
     *
     * @return string|null
     */
    public function getReferenceCustomerId()
    {
        return $this->container['referenceCustomerId'];
    }

    /**
     * Sets referenceCustomerId
     *
     * @param string|null $referenceCustomerId The customer ID in the merchant system. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setReferenceCustomerId($referenceCustomerId)
    {
        $this->container['referenceCustomerId'] = $referenceCustomerId;

        return $this;
    }

    /**
     * Gets alipayUserId
     *
     * @return string|null
     */
    public function getAlipayUserId()
    {
        return $this->container['alipayUserId'];
    }

    /**
     * Sets alipayUserId
     *
     * @param string|null $alipayUserId The Alipay user ID. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setAlipayUserId($alipayUserId)
    {
        $this->container['alipayUserId'] = $alipayUserId;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The email address. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string|null $firstName The first name. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string|null $lastName The last name. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets mobileNo
     *
     * @return string|null
     */
    public function getMobileNo()
    {
        return $this->container['mobileNo'];
    }

    /**
     * Sets mobileNo
     *
     * @param string|null $mobileNo The mobile phone number. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setMobileNo($mobileNo)
    {
        $this->container['mobileNo'] = $mobileNo;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country The country or region code. Maximum length: 8 characters.
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state The state or province. Maximum length: 128 characters.
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city The city. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address The address. Maximum length: 1024 characters.
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets addressDetail
     *
     * @return string|null
     */
    public function getAddressDetail()
    {
        return $this->container['addressDetail'];
    }

    /**
     * Sets addressDetail
     *
     * @param string|null $addressDetail The detailed address information. Maximum length: 2048 characters.
     *
     * @return self
     */
    public function setAddressDetail($addressDetail)
    {
        $this->container['addressDetail'] = $addressDetail;

        return $this;
    }

    /**
     * Gets zipcode
     *
     * @return string|null
     */
    public function getZipcode()
    {
        return $this->container['zipcode'];
    }

    /**
     * Sets zipcode
     *
     * @param string|null $zipcode The ZIP or postal code. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setZipcode($zipcode)
    {
        $this->container['zipcode'] = $zipcode;

        return $this;
    }

    /**
     * Gets shippingName
     *
     * @return string|null
     */
    public function getShippingName()
    {
        return $this->container['shippingName'];
    }

    /**
     * Sets shippingName
     *
     * @param string|null $shippingName The shipping name. Maximum length: 512 characters.
     *
     * @return self
     */
    public function setShippingName($shippingName)
    {
        $this->container['shippingName'] = $shippingName;

        return $this;
    }

    /**
     * Gets shippingPhone
     *
     * @return string|null
     */
    public function getShippingPhone()
    {
        return $this->container['shippingPhone'];
    }

    /**
     * Sets shippingPhone
     *
     * @param string|null $shippingPhone The shipping phone. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setShippingPhone($shippingPhone)
    {
        $this->container['shippingPhone'] = $shippingPhone;

        return $this;
    }

    /**
     * Gets shippingCountry
     *
     * @return string|null
     */
    public function getShippingCountry()
    {
        return $this->container['shippingCountry'];
    }

    /**
     * Sets shippingCountry
     *
     * @param string|null $shippingCountry The shipping country. Maximum length: 8 characters.
     *
     * @return self
     */
    public function setShippingCountry($shippingCountry)
    {
        $this->container['shippingCountry'] = $shippingCountry;

        return $this;
    }

    /**
     * Gets shippingState
     *
     * @return string|null
     */
    public function getShippingState()
    {
        return $this->container['shippingState'];
    }

    /**
     * Sets shippingState
     *
     * @param string|null $shippingState The shipping state. Maximum length: 128 characters.
     *
     * @return self
     */
    public function setShippingState($shippingState)
    {
        $this->container['shippingState'] = $shippingState;

        return $this;
    }

    /**
     * Gets shippingCity
     *
     * @return string|null
     */
    public function getShippingCity()
    {
        return $this->container['shippingCity'];
    }

    /**
     * Sets shippingCity
     *
     * @param string|null $shippingCity The shipping city. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setShippingCity($shippingCity)
    {
        $this->container['shippingCity'] = $shippingCity;

        return $this;
    }

    /**
     * Gets shippingAddress
     *
     * @return string|null
     */
    public function getShippingAddress()
    {
        return $this->container['shippingAddress'];
    }

    /**
     * Sets shippingAddress
     *
     * @param string|null $shippingAddress The shipping address. Maximum length: 1024 characters.
     *
     * @return self
     */
    public function setShippingAddress($shippingAddress)
    {
        $this->container['shippingAddress'] = $shippingAddress;

        return $this;
    }

    /**
     * Gets shippingAddressDetail
     *
     * @return string|null
     */
    public function getShippingAddressDetail()
    {
        return $this->container['shippingAddressDetail'];
    }

    /**
     * Sets shippingAddressDetail
     *
     * @param string|null $shippingAddressDetail The shipping address detail. Maximum length: 2048 characters.
     *
     * @return self
     */
    public function setShippingAddressDetail($shippingAddressDetail)
    {
        $this->container['shippingAddressDetail'] = $shippingAddressDetail;

        return $this;
    }

    /**
     * Gets shippingZipcode
     *
     * @return string|null
     */
    public function getShippingZipcode()
    {
        return $this->container['shippingZipcode'];
    }

    /**
     * Sets shippingZipcode
     *
     * @param string|null $shippingZipcode The shipping zipcode. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setShippingZipcode($shippingZipcode)
    {
        $this->container['shippingZipcode'] = $shippingZipcode;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description. Maximum length: 1024 characters.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency The 3-letter currency code that follows the ISO 4217 standard. Maximum length: 8 characters.
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets preferredLocales
     *
     * @return string|null
     */
    public function getPreferredLocales()
    {
        return $this->container['preferredLocales'];
    }

    /**
     * Sets preferredLocales
     *
     * @param string|null $preferredLocales The preferred language or locale settings. Maximum length: 256 characters.
     *
     * @return self
     */
    public function setPreferredLocales($preferredLocales)
    {
        $this->container['preferredLocales'] = $preferredLocales;

        return $this;
    }

    /**
     * Gets defaultPaymentMethod
     *
     * @return string|null
     */
    public function getDefaultPaymentMethod()
    {
        return $this->container['defaultPaymentMethod'];
    }

    /**
     * Sets defaultPaymentMethod
     *
     * @param string|null $defaultPaymentMethod The default payment method token. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setDefaultPaymentMethod($defaultPaymentMethod)
    {
        $this->container['defaultPaymentMethod'] = $defaultPaymentMethod;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Custom metadata for special use cases. Maximum length: 65535 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
