<?php

namespace Model;

class AttachmentType
{

    const SIGNATURE_AUTHORIZATION_LETTER = "SIGNATURE_AUTHORIZATION_LETTER";
    const ARTICLES_OF_ASSOCIATION = "ARTICLES_OF_ASSOCIATION";
    const LOGO = "LOGO";

    const AUTHORIZER_SIGNATURE_CONFIRMATION_LETTER = "AUTHORIZER_SIGNATURE_CONFIRMATION_LETTER";
    const ASSOCIATION_ARTICLE = "ASSOCIATION_ARTICLE";
    const FINANCIAL_REPORT = "FINANCIAL_REPORT";
    const OWNERSHIP_STRUCTURE_PIC = "OWNERSHIP_STRUCTURE_PIC";
    const ADDRESS_PROOF = "ADDRESS_PROOF";
    const UBO_PROVE = "UBO_PROVE";
    const ENTERPRISE_REGISTRATION = "ENTERPRISE_REGISTRATION";
    const LICENSE_INFO = "LICENSE_INFO";
    const ID_CARD = "ID_CARD";
    const PASSPORT = "PASSPORT";
    const DRIVING_LICENSE = "DRIVING_LICENSE";
    const CPF = "CPF";
    const CNPJ = "CNPJ";

}