<?php

/**
 * payments_createPaymentSession
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * Buyer Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Buyer  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Buyer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'referenceBuyerId' => 'string',
        'buyerName' => '\request\model\UserName',
        'buyerPhoneNo' => 'string',
        'buyerEmail' => 'string',
        'buyerRegistrationTime' => 'string',
        'isAccountVerified' => 'bool',
        'successfulOrderCount' => 'int',
        'buyerPhoneNoContryCode' => 'string',
        'successfulOrderAmount' => '\request\model\Amount',
        'dateOfLastPaidPurchase' => 'string',
        'dateOfFirstPaidPurchase' => 'string',
        'taxIds' => '\request\model\BuyerTaxId[]',
        'businessAddress' => '\request\model\Address'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'referenceBuyerId' => null,
        'buyerName' => null,
        'buyerPhoneNo' => null,
        'buyerEmail' => null,
        'buyerRegistrationTime' => null,
        'isAccountVerified' => null,
        'successfulOrderCount' => null,
        'buyerPhoneNoContryCode' => null,
        'successfulOrderAmount' => null,
        'dateOfLastPaidPurchase' => null,
        'dateOfFirstPaidPurchase' => null,
        'taxIds' => null,
        'businessAddress' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'referenceBuyerId' => false,
        'buyerName' => false,
        'buyerPhoneNo' => false,
        'buyerEmail' => false,
        'buyerRegistrationTime' => false,
        'isAccountVerified' => false,
        'successfulOrderCount' => true,
        'buyerPhoneNoContryCode' => false,
        'successfulOrderAmount' => false,
        'dateOfLastPaidPurchase' => false,
        'dateOfFirstPaidPurchase' => false,
        'taxIds' => false,
        'businessAddress' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referenceBuyerId' => 'referenceBuyerId',
        'buyerName' => 'buyerName',
        'buyerPhoneNo' => 'buyerPhoneNo',
        'buyerEmail' => 'buyerEmail',
        'buyerRegistrationTime' => 'buyerRegistrationTime',
        'isAccountVerified' => 'isAccountVerified',
        'successfulOrderCount' => 'successfulOrderCount',
        'buyerPhoneNoContryCode' => 'buyerPhoneNoContryCode',
        'successfulOrderAmount' => 'successfulOrderAmount',
        'dateOfLastPaidPurchase' => 'dateOfLastPaidPurchase',
        'dateOfFirstPaidPurchase' => 'dateOfFirstPaidPurchase',
        'taxIds' => 'taxIds',
        'businessAddress' => 'businessAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'referenceBuyerId' => 'setReferenceBuyerId',
        'buyerName' => 'setBuyerName',
        'buyerPhoneNo' => 'setBuyerPhoneNo',
        'buyerEmail' => 'setBuyerEmail',
        'buyerRegistrationTime' => 'setBuyerRegistrationTime',
        'isAccountVerified' => 'setIsAccountVerified',
        'successfulOrderCount' => 'setSuccessfulOrderCount',
        'buyerPhoneNoContryCode' => 'setBuyerPhoneNoContryCode',
        'successfulOrderAmount' => 'setSuccessfulOrderAmount',
        'dateOfLastPaidPurchase' => 'setDateOfLastPaidPurchase',
        'dateOfFirstPaidPurchase' => 'setDateOfFirstPaidPurchase',
        'taxIds' => 'setTaxIds',
        'businessAddress' => 'setBusinessAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'referenceBuyerId' => 'getReferenceBuyerId',
        'buyerName' => 'getBuyerName',
        'buyerPhoneNo' => 'getBuyerPhoneNo',
        'buyerEmail' => 'getBuyerEmail',
        'buyerRegistrationTime' => 'getBuyerRegistrationTime',
        'isAccountVerified' => 'getIsAccountVerified',
        'successfulOrderCount' => 'getSuccessfulOrderCount',
        'buyerPhoneNoContryCode' => 'getBuyerPhoneNoContryCode',
        'successfulOrderAmount' => 'getSuccessfulOrderAmount',
        'dateOfLastPaidPurchase' => 'getDateOfLastPaidPurchase',
        'dateOfFirstPaidPurchase' => 'getDateOfFirstPaidPurchase',
        'taxIds' => 'getTaxIds',
        'businessAddress' => 'getBusinessAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('referenceBuyerId', $data ?? [], null);
        $this->setIfExists('buyerName', $data ?? [], null);
        $this->setIfExists('buyerPhoneNo', $data ?? [], null);
        $this->setIfExists('buyerEmail', $data ?? [], null);
        $this->setIfExists('buyerRegistrationTime', $data ?? [], null);
        $this->setIfExists('isAccountVerified', $data ?? [], null);
        $this->setIfExists('successfulOrderCount', $data ?? [], null);
        $this->setIfExists('buyerPhoneNoContryCode', $data ?? [], null);
        $this->setIfExists('successfulOrderAmount', $data ?? [], null);
        $this->setIfExists('dateOfLastPaidPurchase', $data ?? [], null);
        $this->setIfExists('dateOfFirstPaidPurchase', $data ?? [], null);
        $this->setIfExists('taxIds', $data ?? [], null);
        $this->setIfExists('businessAddress', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets referenceBuyerId
     *
     * @return string|null
     */
    public function getReferenceBuyerId()
    {
        return $this->container['referenceBuyerId'];
    }

    /**
     * Sets referenceBuyerId
     *
     * @param string|null $referenceBuyerId The unique ID to identify the buyer.  Note: Specify this parameter when you want to use the promotion offered by Antom to this order.  More information:  Maximum length: 64 characters
     *
     * @return self
     */
    public function setReferenceBuyerId($referenceBuyerId)
    {
        $this->container['referenceBuyerId'] = $referenceBuyerId;

        return $this;
    }

    /**
     * Gets buyerName
     *
     * @return \model\UserName|null
     */
    public function getBuyerName()
    {
        return $this->container['buyerName'];
    }

    /**
     * Sets buyerName
     *
     * @param \model\UserName|null $buyerName buyerName
     *
     * @return self
     */
    public function setBuyerName($buyerName)
    {
        $this->container['buyerName'] = $buyerName;

        return $this;
    }

    /**
     * Gets buyerPhoneNo
     *
     * @return string|null
     */
    public function getBuyerPhoneNo()
    {
        return $this->container['buyerPhoneNo'];
    }

    /**
     * Sets buyerPhoneNo
     *
     * @param string|null $buyerPhoneNo The mobile phone number of the buyer.  Specify this parameter when one of the following conditions is met:  You require risk control. The value of paymentMethodType is CARD. Providing this information helps to increase the accuracy of anti-money laundering and fraud detection, and increase payment success rates.   More information:  Maximum length: 24 characters
     *
     * @return self
     */
    public function setBuyerPhoneNo($buyerPhoneNo)
    {
        $this->container['buyerPhoneNo'] = $buyerPhoneNo;

        return $this;
    }

    /**
     * Gets buyerEmail
     *
     * @return string|null
     */
    public function getBuyerEmail()
    {
        return $this->container['buyerEmail'];
    }

    /**
     * Sets buyerEmail
     *
     * @param string|null $buyerEmail The email of the buyer.  Specify this parameter:  When you require risk control. When the value of paymentMethodType is CARD. Providing this information helps to increase the accuracy of anti-money laundering and fraud detection, and increase payment success rates.   More information:  Maximum length: 64 characters
     *
     * @return self
     */
    public function setBuyerEmail($buyerEmail)
    {
        $this->container['buyerEmail'] = $buyerEmail;

        return $this;
    }

    /**
     * Gets buyerRegistrationTime
     *
     * @return string|null
     */
    public function getBuyerRegistrationTime()
    {
        return $this->container['buyerRegistrationTime'];
    }

    /**
     * Sets buyerRegistrationTime
     *
     * @param string|null $buyerRegistrationTime The time when the buyer registered your account. Specify this parameter if you require risk control. Providing this information helps to increase the accuracy of anti-money laundering and fraud detection, and increase payment success rates.    More information:  Maximum length: 64 characters The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\".
     *
     * @return self
     */
    public function setBuyerRegistrationTime($buyerRegistrationTime)
    {
        $this->container['buyerRegistrationTime'] = $buyerRegistrationTime;

        return $this;
    }

    /**
     * Gets isAccountVerified
     *
     * @return bool|null
     */
    public function getIsAccountVerified()
    {
        return $this->container['isAccountVerified'];
    }

    /**
     * Sets isAccountVerified
     *
     * @param bool|null $isAccountVerified isAccountVerified
     *
     * @return self
     */
    public function setIsAccountVerified($isAccountVerified)
    {
        $this->container['isAccountVerified'] = $isAccountVerified;

        return $this;
    }

    /**
     * Gets successfulOrderCount
     *
     * @return int|null
     */
    public function getSuccessfulOrderCount()
    {
        return $this->container['successfulOrderCount'];
    }

    /**
     * Sets successfulOrderCount
     *
     * @param int|null $successfulOrderCount successfulOrderCount
     *
     * @return self
     */
    public function setSuccessfulOrderCount($successfulOrderCount)
    {
        $this->container['successfulOrderCount'] = $successfulOrderCount;

        return $this;
    }

    /**
     * Gets buyerPhoneNoContryCode
     *
     * @return string|null
     */
    public function getBuyerPhoneNoContryCode()
    {
        return $this->container['buyerPhoneNoContryCode'];
    }

    /**
     * Sets buyerPhoneNoContryCode
     *
     * @param string|null $buyerPhoneNoContryCode 用于指定买家电话号码的国家代码，当支付方式为STCPAY时为必填字段
     *
     * @return self
     */
    public function setBuyerPhoneNoContryCode($buyerPhoneNoContryCode)
    {
        $this->container['buyerPhoneNoContryCode'] = $buyerPhoneNoContryCode;

        return $this;
    }

    /**
     * Gets successfulOrderAmount
     *
     * @return \model\Amount|null
     */
    public function getSuccessfulOrderAmount()
    {
        return $this->container['successfulOrderAmount'];
    }

    /**
     * Sets successfulOrderAmount
     *
     * @param \model\Amount|null $successfulOrderAmount successfulOrderAmount
     *
     * @return self
     */
    public function setSuccessfulOrderAmount($successfulOrderAmount)
    {
        $this->container['successfulOrderAmount'] = $successfulOrderAmount;

        return $this;
    }

    /**
     * Gets dateOfLastPaidPurchase
     *
     * @return string|null
     */
    public function getDateOfLastPaidPurchase()
    {
        return $this->container['dateOfLastPaidPurchase'];
    }

    /**
     * Sets dateOfLastPaidPurchase
     *
     * @param string|null $dateOfLastPaidPurchase The date and time of the buyer's last paid purchase. When using KLARNA for an e-commerce merchant, this field is required. The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\".
     *
     * @return self
     */
    public function setDateOfLastPaidPurchase($dateOfLastPaidPurchase)
    {
        $this->container['dateOfLastPaidPurchase'] = $dateOfLastPaidPurchase;

        return $this;
    }

    /**
     * Gets dateOfFirstPaidPurchase
     *
     * @return string|null
     */
    public function getDateOfFirstPaidPurchase()
    {
        return $this->container['dateOfFirstPaidPurchase'];
    }

    /**
     * Sets dateOfFirstPaidPurchase
     *
     * @param string|null $dateOfFirstPaidPurchase The date and time of the buyer's first paid purchase. When using KLARNA for an e-commerce merchant, this field is required. The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\".
     *
     * @return self
     */
    public function setDateOfFirstPaidPurchase($dateOfFirstPaidPurchase)
    {
        $this->container['dateOfFirstPaidPurchase'] = $dateOfFirstPaidPurchase;

        return $this;
    }

    /**
     * Gets taxIds
     *
     * @return \model\BuyerTaxId[]|null
     */
    public function getTaxIds()
    {
        return $this->container['taxIds'];
    }

    /**
     * Sets taxIds
     *
     * @param \model\BuyerTaxId[]|null $taxIds For createPaymentSession, these buyer tax IDs are used for B2B or reverse-charge determination when automatic tax is active. If omitted, null, invalid, or unusable, Antom calculates tax as B2C instead of rejecting the payment session. Because Buyer is a shared SDK model, omit this field in APIs that do not explicitly document support. Maximum size: 10.
     *
     * @return self
     */
    public function setTaxIds($taxIds)
    {
        $this->container['taxIds'] = $taxIds;

        return $this;
    }

    /**
     * Gets businessAddress
     *
     * @return \model\Address|null
     */
    public function getBusinessAddress()
    {
        return $this->container['businessAddress'];
    }

    /**
     * Sets businessAddress
     *
     * @param \model\Address|null $businessAddress businessAddress
     *
     * @return self
     */
    public function setBusinessAddress($businessAddress)
    {
        $this->container['businessAddress'] = $businessAddress;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
