<?php

/**
 * vaults_inquireVaulting
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * CardBrand Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class CardBrand
{
    public const VISA = 'VISA';
    public const MASTERCARD = 'MASTERCARD';
    public const MAESTRO = 'MAESTRO';
    public const AMEX = 'AMEX';
    public const JCB = 'JCB';
    public const DINERS = 'DINERS';
    public const DISCOVER = 'DISCOVER';
    public const CUP = 'CUP';
    public const MIR = 'MIR';
    public const ELO = 'ELO';
    public const HIPERCARD = 'HIPERCARD';
    public const TROY = 'TROY';

    private $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function VISA(): self
    {
        return new self(self::VISA);
    }
    public static function MASTERCARD(): self
    {
        return new self(self::MASTERCARD);
    }
    public static function MAESTRO(): self
    {
        return new self(self::MAESTRO);
    }
    public static function AMEX(): self
    {
        return new self(self::AMEX);
    }
    public static function JCB(): self
    {
        return new self(self::JCB);
    }
    public static function DINERS(): self
    {
        return new self(self::DINERS);
    }
    public static function DISCOVER(): self
    {
        return new self(self::DISCOVER);
    }
    public static function CUP(): self
    {
        return new self(self::CUP);
    }
    public static function MIR(): self
    {
        return new self(self::MIR);
    }
    public static function ELO(): self
    {
        return new self(self::ELO);
    }
    public static function HIPERCARD(): self
    {
        return new self(self::HIPERCARD);
    }
    public static function TROY(): self
    {
        return new self(self::TROY);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
