<?php

/**
 * aba-inquireCardTransactionEvent
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * CardTransactionEventFilterType Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class CardTransactionEventFilterType
{
    public const AUTH = 'AUTH';
    public const AUTH_CANCEL = 'AUTH_CANCEL';
    public const CAPTURE = 'CAPTURE';
    public const REFUND = 'REFUND';
    public const CHARGEBACK = 'CHARGEBACK';
    public const REPAYMENT = 'REPAYMENT';

    public $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function AUTH(): self
    {
        return new self(self::AUTH);
    }
    public static function AUTH_CANCEL(): self
    {
        return new self(self::AUTH_CANCEL);
    }
    public static function CAPTURE(): self
    {
        return new self(self::CAPTURE);
    }
    public static function REFUND(): self
    {
        return new self(self::REFUND);
    }
    public static function CHARGEBACK(): self
    {
        return new self(self::CHARGEBACK);
    }
    public static function REPAYMENT(): self
    {
        return new self(self::REPAYMENT);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
