<?php

/**
 * payments_createPaymentSession
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Model;

/**
 * ClassType Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class ClassType
{
    public const FIRSTLEVEL = 'FIRSTLEVEL';
    public const SECONDLEVEL = 'SECONDLEVEL';
    public const THIRDLEVEL = 'THIRDLEVEL';

    public $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function FIRSTLEVEL(): self
    {
        return new self(self::FIRSTLEVEL);
    }
    public static function SECONDLEVEL(): self
    {
        return new self(self::SECONDLEVEL);
    }
    public static function THIRDLEVEL(): self
    {
        return new self(self::THIRDLEVEL);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
