<?php

/**
 * payments_createPaymentSession
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * Leg Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Leg  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Leg';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'departureTime' => 'string',
        'arrivalTime' => 'string',
        'departureAddress' => '\request\model\Address',
        'arrivalAddress' => '\request\model\Address',
        'carrierName' => 'string',
        'carrierNo' => 'string',
        'classType' => '\request\model\ClassType',
        'departureAirportCode' => 'string',
        'arrivalAirportCode' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'departureTime' => null,
        'arrivalTime' => null,
        'departureAddress' => null,
        'arrivalAddress' => null,
        'carrierName' => null,
        'carrierNo' => null,
        'classType' => null,
        'departureAirportCode' => null,
        'arrivalAirportCode' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'departureTime' => false,
        'arrivalTime' => false,
        'departureAddress' => false,
        'arrivalAddress' => false,
        'carrierName' => false,
        'carrierNo' => false,
        'classType' => false,
        'departureAirportCode' => false,
        'arrivalAirportCode' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'departureTime' => 'departureTime',
        'arrivalTime' => 'arrivalTime',
        'departureAddress' => 'departureAddress',
        'arrivalAddress' => 'arrivalAddress',
        'carrierName' => 'carrierName',
        'carrierNo' => 'carrierNo',
        'classType' => 'classType',
        'departureAirportCode' => 'departureAirportCode',
        'arrivalAirportCode' => 'arrivalAirportCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'departureTime' => 'setDepartureTime',
        'arrivalTime' => 'setArrivalTime',
        'departureAddress' => 'setDepartureAddress',
        'arrivalAddress' => 'setArrivalAddress',
        'carrierName' => 'setCarrierName',
        'carrierNo' => 'setCarrierNo',
        'classType' => 'setClassType',
        'departureAirportCode' => 'setDepartureAirportCode',
        'arrivalAirportCode' => 'setArrivalAirportCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'departureTime' => 'getDepartureTime',
        'arrivalTime' => 'getArrivalTime',
        'departureAddress' => 'getDepartureAddress',
        'arrivalAddress' => 'getArrivalAddress',
        'carrierName' => 'getCarrierName',
        'carrierNo' => 'getCarrierNo',
        'classType' => 'getClassType',
        'departureAirportCode' => 'getDepartureAirportCode',
        'arrivalAirportCode' => 'getArrivalAirportCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('departureTime', $data ?? [], null);
        $this->setIfExists('arrivalTime', $data ?? [], null);
        $this->setIfExists('departureAddress', $data ?? [], null);
        $this->setIfExists('arrivalAddress', $data ?? [], null);
        $this->setIfExists('carrierName', $data ?? [], null);
        $this->setIfExists('carrierNo', $data ?? [], null);
        $this->setIfExists('classType', $data ?? [], null);
        $this->setIfExists('departureAirportCode', $data ?? [], null);
        $this->setIfExists('arrivalAirportCode', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets departureTime
     *
     * @return string|null
     */
    public function getDepartureTime()
    {
        return $this->container['departureTime'];
    }

    /**
     * Sets departureTime
     *
     * @param string|null $departureTime Time of departure for this leg of the trip.  More information:  The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\".
     *
     * @return self
     */
    public function setDepartureTime($departureTime)
    {
        $this->container['departureTime'] = $departureTime;

        return $this;
    }

    /**
     * Gets arrivalTime
     *
     * @return string|null
     */
    public function getArrivalTime()
    {
        return $this->container['arrivalTime'];
    }

    /**
     * Sets arrivalTime
     *
     * @param string|null $arrivalTime Time of arrival for this leg of the trip.  More information:  The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\".
     *
     * @return self
     */
    public function setArrivalTime($arrivalTime)
    {
        $this->container['arrivalTime'] = $arrivalTime;

        return $this;
    }

    /**
     * Gets departureAddress
     *
     * @return \request\model\Address|null
     */
    public function getDepartureAddress()
    {
        return $this->container['departureAddress'];
    }

    /**
     * Sets departureAddress
     *
     * @param \request\model\Address|null $departureAddress departureAddress
     *
     * @return self
     */
    public function setDepartureAddress($departureAddress)
    {
        $this->container['departureAddress'] = $departureAddress;

        return $this;
    }

    /**
     * Gets arrivalAddress
     *
     * @return \request\model\Address|null
     */
    public function getArrivalAddress()
    {
        return $this->container['arrivalAddress'];
    }

    /**
     * Sets arrivalAddress
     *
     * @param \request\model\Address|null $arrivalAddress arrivalAddress
     *
     * @return self
     */
    public function setArrivalAddress($arrivalAddress)
    {
        $this->container['arrivalAddress'] = $arrivalAddress;

        return $this;
    }

    /**
     * Gets carrierName
     *
     * @return string|null
     */
    public function getCarrierName()
    {
        return $this->container['carrierName'];
    }

    /**
     * Sets carrierName
     *
     * @param string|null $carrierName Company name of the transportation service provider for this leg of the trip.  More information:  Maximum length: 128 characters
     *
     * @return self
     */
    public function setCarrierName($carrierName)
    {
        $this->container['carrierName'] = $carrierName;

        return $this;
    }

    /**
     * Gets carrierNo
     *
     * @return string|null
     */
    public function getCarrierNo()
    {
        return $this->container['carrierNo'];
    }

    /**
     * Sets carrierNo
     *
     * @param string|null $carrierNo Code for the carrier for this leg of the trip.  More information:  Maximum length: 64 characters
     *
     * @return self
     */
    public function setCarrierNo($carrierNo)
    {
        $this->container['carrierNo'] = $carrierNo;

        return $this;
    }

    /**
     * Gets classType
     *
     * @return \request\model\ClassType|null
     */
    public function getClassType()
    {
        return $this->container['classType'];
    }

    /**
     * Sets classType
     *
     * @param \request\model\ClassType|null $classType classType
     *
     * @return self
     */
    public function setClassType($classType)
    {
        $this->container['classType'] = $classType;

        return $this;
    }

    /**
     * Gets departureAirportCode
     *
     * @return string|null
     */
    public function getDepartureAirportCode()
    {
        return $this->container['departureAirportCode'];
    }

    /**
     * Sets departureAirportCode
     *
     * @param string|null $departureAirportCode IATA code for the originating airport for this leg of the trip.  More information:  Maximum length: 8 characters
     *
     * @return self
     */
    public function setDepartureAirportCode($departureAirportCode)
    {
        $this->container['departureAirportCode'] = $departureAirportCode;

        return $this;
    }

    /**
     * Gets arrivalAirportCode
     *
     * @return string|null
     */
    public function getArrivalAirportCode()
    {
        return $this->container['arrivalAirportCode'];
    }

    /**
     * Sets arrivalAirportCode
     *
     * @param string|null $arrivalAirportCode IATA code for the destination airport for this leg of the trip.  More information:  Maximum length: 8 characters
     *
     * @return self
     */
    public function setArrivalAirportCode($arrivalAirportCode)
    {
        $this->container['arrivalAirportCode'] = $arrivalAirportCode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
