<?php

namespace Model;

class PassengerIdType
//    PASSPORT, NATIONAL_ID_CARD, DRIVER_LICENSE, MILITARY_ID, GREEN_CARD, TRAVEL_DOCUMENT, ALIEN_REGISTRATION_CARD, BIRTH_CERTIFICATE, OTHERS
{
    const PASSPORT = "PASSPORT";

    const NATIONAL_ID_CARD = "NATIONAL_ID_CARD";

    const  DRIVER_LICENSE = "DRIVER_LICENSE";

    const  MILITARY_ID = "MILITARY_ID";

    const GREEN_CARD = "GREEN_CARD";

    const TRAVEL_DOCUMENT = "TRAVEL_DOCUMENT";

    const  ALIEN_REGISTRATION_CARD = "ALIEN_REGISTRATION_CARD";

    const BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE";

    const OTHERS = "OTHERS";



}