<?php

/**
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * PaymentMethodCategoryType Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class PaymentMethodCategoryType
{
    public const ALIPAY_PLUS = 'ALIPAY_PLUS';
    public const WALLET = 'WALLET';
    public const MOBILE_BANKING_APP = 'MOBILE_BANKING_APP';
    public const BANK_TRANSFER = 'BANK_TRANSFER';
    public const ONLINE_BANKING = 'ONLINE_BANKING';
    public const CARD = 'CARD';
    public const OTC = 'OTC';

    public $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function ALIPAY_PLUS(): self
    {
        return new self(self::ALIPAY_PLUS);
    }
    public static function WALLET(): self
    {
        return new self(self::WALLET);
    }
    public static function MOBILE_BANKING_APP(): self
    {
        return new self(self::MOBILE_BANKING_APP);
    }
    public static function BANK_TRANSFER(): self
    {
        return new self(self::BANK_TRANSFER);
    }
    public static function ONLINE_BANKING(): self
    {
        return new self(self::ONLINE_BANKING);
    }
    public static function CARD(): self
    {
        return new self(self::CARD);
    }
    public static function OTC(): self
    {
        return new self(self::OTC);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
