<?php

/**
 * v1_payments_reserve_updateRule
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * RuleStatus Class Doc Comment
 *
 * @category Class
 * @description The reserve rule configuration status. This status does not indicate whether retained funds have been released.
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class RuleStatus
{
    public const ACTIVE = 'ACTIVE';
    public const DISABLED = 'DISABLED';

    public $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function ACTIVE(): self
    {
        return new self(self::ACTIVE);
    }
    public static function DISABLED(): self
    {
        return new self(self::DISABLED);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
