<?php

namespace Model;
class ScopeType
{

    const BASE_USER_INFO = "BASE_USER_INFO";
    const AGREEMENT_PAY = "AGREEMENT_PAY";
    const USER_INFO = "USER_INFO";
    const USER_LOGIN_ID = "USER_LOGIN_ID";
    const HASH_LOGIN_ID = "HASH_LOGIN_ID";
    const SEND_OTP = "SEND_OTP";
    const TAOBAO_REBIND = "TAOBAO_REBIND";

    const ABA_DIRECT_PAYMENT_AUTHORIZATION = "ABA_DIRECT_PAYMENT_AUTHORIZATION";
    const  ABA_LOAN_AUTHORIZATION = "ABA_LOAN_AUTHORIZATION";

}