<?php

/**
 * marketplace_settle
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * SettleToType Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class SettleToType
{
    public const SELLER = 'SELLER';
    public const MARKETPLACE = 'MARKETPLACE';

    public $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function SELLER(): self
    {
        return new self(self::SELLER);
    }
    public static function MARKETPLACE(): self
    {
        return new self(self::MARKETPLACE);
    }

    public function getValue(): string
    {
        return $this->value;
    }
    public function __toString(): string
    {
        return $this->value;
    }


}
