<?php

/**
 * v1_tax_inquireCalculation
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * TaxCalculatedLineItem Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TaxCalculatedLineItem  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TaxCalculatedLineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'goodsReferenceId' => 'string',
        'unitAmount' => 'string',
        'amount' => 'string',
        'quantity' => 'int',
        'taxCode' => 'string',
        'taxBehavior' => 'string',
        'taxAmount' => 'string',
        'taxBreakdown' => '\request\model\TaxBreakdown[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'goodsReferenceId' => null,
        'unitAmount' => null,
        'amount' => null,
        'quantity' => null,
        'taxCode' => null,
        'taxBehavior' => null,
        'taxAmount' => null,
        'taxBreakdown' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'goodsReferenceId' => false,
        'unitAmount' => false,
        'amount' => false,
        'quantity' => true,
        'taxCode' => false,
        'taxBehavior' => false,
        'taxAmount' => false,
        'taxBreakdown' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'goodsReferenceId' => 'goodsReferenceId',
        'unitAmount' => 'unitAmount',
        'amount' => 'amount',
        'quantity' => 'quantity',
        'taxCode' => 'taxCode',
        'taxBehavior' => 'taxBehavior',
        'taxAmount' => 'taxAmount',
        'taxBreakdown' => 'taxBreakdown'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'goodsReferenceId' => 'setGoodsReferenceId',
        'unitAmount' => 'setUnitAmount',
        'amount' => 'setAmount',
        'quantity' => 'setQuantity',
        'taxCode' => 'setTaxCode',
        'taxBehavior' => 'setTaxBehavior',
        'taxAmount' => 'setTaxAmount',
        'taxBreakdown' => 'setTaxBreakdown'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'goodsReferenceId' => 'getGoodsReferenceId',
        'unitAmount' => 'getUnitAmount',
        'amount' => 'getAmount',
        'quantity' => 'getQuantity',
        'taxCode' => 'getTaxCode',
        'taxBehavior' => 'getTaxBehavior',
        'taxAmount' => 'getTaxAmount',
        'taxBreakdown' => 'getTaxBreakdown'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('goodsReferenceId', $data ?? [], null);
        $this->setIfExists('unitAmount', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('taxCode', $data ?? [], null);
        $this->setIfExists('taxBehavior', $data ?? [], null);
        $this->setIfExists('taxAmount', $data ?? [], null);
        $this->setIfExists('taxBreakdown', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['goodsReferenceId'] === null) {
            $invalidProperties[] = "'goodsReferenceId' can't be null";
        }
        if ($this->container['unitAmount'] === null) {
            $invalidProperties[] = "'unitAmount' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['taxBehavior'] === null) {
            $invalidProperties[] = "'taxBehavior' can't be null";
        }
        if ($this->container['taxAmount'] === null) {
            $invalidProperties[] = "'taxAmount' can't be null";
        }
        if ($this->container['taxBreakdown'] === null) {
            $invalidProperties[] = "'taxBreakdown' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets goodsReferenceId
     *
     * @return string
     */
    public function getGoodsReferenceId()
    {
        return $this->container['goodsReferenceId'];
    }

    /**
     * Sets goodsReferenceId
     *
     * @param string $goodsReferenceId The goods reference ID. Maximum length: 128 characters.
     *
     * @return self
     */
    public function setGoodsReferenceId($goodsReferenceId)
    {
        $this->container['goodsReferenceId'] = $goodsReferenceId;

        return $this;
    }

    /**
     * Gets unitAmount
     *
     * @return string
     */
    public function getUnitAmount()
    {
        return $this->container['unitAmount'];
    }

    /**
     * Sets unitAmount
     *
     * @param string $unitAmount The unit amount. Maximum length: 19 characters.
     *
     * @return self
     */
    public function setUnitAmount($unitAmount)
    {
        $this->container['unitAmount'] = $unitAmount;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param string $amount The amount. Maximum length: 19 characters.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity The quantity.
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets taxCode
     *
     * @return string|null
     */
    public function getTaxCode()
    {
        return $this->container['taxCode'];
    }

    /**
     * Sets taxCode
     *
     * @param string|null $taxCode The tax code. Maximum length: 32 characters.
     *
     * @return self
     */
    public function setTaxCode($taxCode)
    {
        $this->container['taxCode'] = $taxCode;

        return $this;
    }

    /**
     * Gets taxBehavior
     *
     * @return string
     */
    public function getTaxBehavior()
    {
        return $this->container['taxBehavior'];
    }

    /**
     * Sets taxBehavior
     *
     * @param string $taxBehavior The tax behavior. Maximum length: 16 characters.
     *
     * @return self
     */
    public function setTaxBehavior($taxBehavior)
    {
        $this->container['taxBehavior'] = $taxBehavior;

        return $this;
    }

    /**
     * Gets taxAmount
     *
     * @return string
     */
    public function getTaxAmount()
    {
        return $this->container['taxAmount'];
    }

    /**
     * Sets taxAmount
     *
     * @param string $taxAmount The tax amount. Maximum length: 19 characters.
     *
     * @return self
     */
    public function setTaxAmount($taxAmount)
    {
        $this->container['taxAmount'] = $taxAmount;

        return $this;
    }

    /**
     * Gets taxBreakdown
     *
     * @return \model\TaxBreakdown[]
     */
    public function getTaxBreakdown()
    {
        return $this->container['taxBreakdown'];
    }

    /**
     * Sets taxBreakdown
     *
     * @param \model\TaxBreakdown[] $taxBreakdown The tax breakdown.
     *
     * @return self
     */
    public function setTaxBreakdown($taxBreakdown)
    {
        $this->container['taxBreakdown'] = $taxBreakdown;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
