<?php

/**
 * /ams/v1/subscriptions/inquireSubscriptionList
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Request\subscription;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayInquireSubscriptionListRequest Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayInquireSubscriptionListRequest   extends AlipayRequest  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayInquireSubscriptionListRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'merchantAccountId' => 'string',
        'startTimeFrom' => '\DateTime',
        'startTimeTo' => '\DateTime',
        'statuses' => '\request\model\SubscriptionStatus[]',
        'paymentMethodTypes' => 'string[]',
        'currencies' => 'string[]',
        'periodTypes' => '\request\model\PeriodType[]',
        'currentPage' => 'int',
        'pageSize' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'merchantAccountId' => null,
        'startTimeFrom' => null,
        'startTimeTo' => null,
        'statuses' => null,
        'paymentMethodTypes' => null,
        'currencies' => null,
        'periodTypes' => null,
        'currentPage' => null,
        'pageSize' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'merchantAccountId' => false,
        'startTimeFrom' => false,
        'startTimeTo' => false,
        'statuses' => false,
        'paymentMethodTypes' => false,
        'currencies' => false,
        'periodTypes' => false,
        'currentPage' => true,
        'pageSize' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchantAccountId' => 'merchantAccountId',
        'startTimeFrom' => 'startTimeFrom',
        'startTimeTo' => 'startTimeTo',
        'statuses' => 'statuses',
        'paymentMethodTypes' => 'paymentMethodTypes',
        'currencies' => 'currencies',
        'periodTypes' => 'periodTypes',
        'currentPage' => 'currentPage',
        'pageSize' => 'pageSize'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchantAccountId' => 'setMerchantAccountId',
        'startTimeFrom' => 'setStartTimeFrom',
        'startTimeTo' => 'setStartTimeTo',
        'statuses' => 'setStatuses',
        'paymentMethodTypes' => 'setPaymentMethodTypes',
        'currencies' => 'setCurrencies',
        'periodTypes' => 'setPeriodTypes',
        'currentPage' => 'setCurrentPage',
        'pageSize' => 'setPageSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchantAccountId' => 'getMerchantAccountId',
        'startTimeFrom' => 'getStartTimeFrom',
        'startTimeTo' => 'getStartTimeTo',
        'statuses' => 'getStatuses',
        'paymentMethodTypes' => 'getPaymentMethodTypes',
        'currencies' => 'getCurrencies',
        'periodTypes' => 'getPeriodTypes',
        'currentPage' => 'getCurrentPage',
        'pageSize' => 'getPageSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('merchantAccountId', $data ?? [], null);
        $this->setIfExists('startTimeFrom', $data ?? [], null);
        $this->setIfExists('startTimeTo', $data ?? [], null);
        $this->setIfExists('statuses', $data ?? [], null);
        $this->setIfExists('paymentMethodTypes', $data ?? [], null);
        $this->setIfExists('currencies', $data ?? [], null);
        $this->setIfExists('periodTypes', $data ?? [], null);
        $this->setIfExists('currentPage', $data ?? [], null);
        $this->setIfExists('pageSize', $data ?? [], null);

         $this->setPath("/ams/api/v1/subscriptions/inquireSubscriptionList"); 
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchantAccountId
     *
     * @return string|null
     */
    public function getMerchantAccountId()
    {
        return $this->container['merchantAccountId'];
    }

    /**
     * Sets merchantAccountId
     *
     * @param string|null $merchantAccountId A unique ID to identify a specific merchant account.
     *
     * @return self
     */
    public function setMerchantAccountId($merchantAccountId)
    {
        $this->container['merchantAccountId'] = $merchantAccountId;

        return $this;
    }

    /**
     * Gets startTimeFrom
     *
     * @return \DateTime|null
     */
    public function getStartTimeFrom()
    {
        return $this->container['startTimeFrom'];
    }

    /**
     * Sets startTimeFrom
     *
     * @param \DateTime|null $startTimeFrom Filter Subscriptions with a start date after the specified date. The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\". Default if not provided: 7 days ago.
     *
     * @return self
     */
    public function setStartTimeFrom($startTimeFrom)
    {
        $this->container['startTimeFrom'] = $startTimeFrom;

        return $this;
    }

    /**
     * Gets startTimeTo
     *
     * @return \DateTime|null
     */
    public function getStartTimeTo()
    {
        return $this->container['startTimeTo'];
    }

    /**
     * Sets startTimeTo
     *
     * @param \DateTime|null $startTimeTo Filter Subscriptions with a start date before the specified date. The value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\". Default if not provided: current time.
     *
     * @return self
     */
    public function setStartTimeTo($startTimeTo)
    {
        $this->container['startTimeTo'] = $startTimeTo;

        return $this;
    }

    /**
     * Gets statuses
     *
     * @return \model\SubscriptionStatus[]|null
     */
    public function getStatuses()
    {
        return $this->container['statuses'];
    }

    /**
     * Sets statuses
     *
     * @param \model\SubscriptionStatus[]|null $statuses Filter Subscriptions whose status matches any value in the list. Default if not provided: Get all subscriptions whose status is in [ACTIVE, CANCELLED, TERMINATED].
     *
     * @return self
     */
    public function setStatuses($statuses)
    {
        $this->container['statuses'] = $statuses;

        return $this;
    }

    /**
     * Gets paymentMethodTypes
     *
     * @return string[]|null
     */
    public function getPaymentMethodTypes()
    {
        return $this->container['paymentMethodTypes'];
    }

    /**
     * Sets paymentMethodTypes
     *
     * @param string[]|null $paymentMethodTypes Filter Subscriptions whose payment method matches any value in the list. See Payment methods to check the valid values. Default if not provided: Subscriptions of all payment method are returned.
     *
     * @return self
     */
    public function setPaymentMethodTypes($paymentMethodTypes)
    {
        $this->container['paymentMethodTypes'] = $paymentMethodTypes;

        return $this;
    }

    /**
     * Gets currencies
     *
     * @return string[]|null
     */
    public function getCurrencies()
    {
        return $this->container['currencies'];
    }

    /**
     * Sets currencies
     *
     * @param string[]|null $currencies Filter Subscriptions whose currency matches any value in the list. The transaction currency, which is a 3-letter currency code that follows the ISO 4217 standard. Default if not provided: Subscriptions of all currency are returned.
     *
     * @return self
     */
    public function setCurrencies($currencies)
    {
        $this->container['currencies'] = $currencies;

        return $this;
    }

    /**
     * Gets periodTypes
     *
     * @return \model\PeriodType[]|null
     */
    public function getPeriodTypes()
    {
        return $this->container['periodTypes'];
    }

    /**
     * Sets periodTypes
     *
     * @param \model\PeriodType[]|null $periodTypes Filter Subscriptions whose periodType matches any value in the list. Default if not provided: Subscriptions of all periodType are returned.
     *
     * @return self
     */
    public function setPeriodTypes($periodTypes)
    {
        $this->container['periodTypes'] = $periodTypes;

        return $this;
    }

    /**
     * Gets currentPage
     *
     * @return int|null
     */
    public function getCurrentPage()
    {
        return $this->container['currentPage'];
    }

    /**
     * Sets currentPage
     *
     * @param int|null $currentPage Current page number. Default if not provided: Get all subscriptions in page 1.
     *
     * @return self
     */
    public function setCurrentPage($currentPage)
    {
        $this->container['currentPage'] = $currentPage;

        return $this;
    }

    /**
     * Gets pageSize
     *
     * @return int|null
     */
    public function getPageSize()
    {
        return $this->container['pageSize'];
    }

    /**
     * Sets pageSize
     *
     * @param int|null $pageSize Page size. Default if not provided: Page size of 10.
     *
     * @return self
     */
    public function setPageSize($pageSize)
    {
        $this->container['pageSize'] = $pageSize;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
