<?php

/**
 * v1_billing_creditNote_inquireDetails
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Response\billing;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayCreditNoteInquireDetailsResponse Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayCreditNoteInquireDetailsResponse  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayCreditNoteInquireDetailsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'result' => '\request\model\Result',
        'creditNoteId' => 'string',
        'creditNoteRequestId' => 'string',
        'invoiceId' => 'string',
        'customerId' => 'string',
        'type' => 'string',
        'status' => 'string',
        'totalAmount' => '\request\model\Amount',
        'refundStatus' => 'string',
        'refundId' => 'string',
        'reason' => 'string',
        'reasonDescription' => 'string',
        'refundDestination' => 'string',
        'effectiveDate' => 'string',
        'memo' => 'string',
        'items' => '\request\model\CreditNoteInquireDetailsItems',
        'issuedAt' => 'string',
        'refundedAt' => 'string',
        'voidedAt' => 'string',
        'createdAt' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'result' => null,
        'creditNoteId' => null,
        'creditNoteRequestId' => null,
        'invoiceId' => null,
        'customerId' => null,
        'type' => null,
        'status' => null,
        'totalAmount' => null,
        'refundStatus' => null,
        'refundId' => null,
        'reason' => null,
        'reasonDescription' => null,
        'refundDestination' => null,
        'effectiveDate' => null,
        'memo' => null,
        'items' => null,
        'issuedAt' => null,
        'refundedAt' => null,
        'voidedAt' => null,
        'createdAt' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'result' => false,
        'creditNoteId' => false,
        'creditNoteRequestId' => false,
        'invoiceId' => false,
        'customerId' => false,
        'type' => false,
        'status' => false,
        'totalAmount' => false,
        'refundStatus' => false,
        'refundId' => false,
        'reason' => false,
        'reasonDescription' => false,
        'refundDestination' => false,
        'effectiveDate' => false,
        'memo' => false,
        'items' => false,
        'issuedAt' => false,
        'refundedAt' => false,
        'voidedAt' => false,
        'createdAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'result' => 'result',
        'creditNoteId' => 'creditNoteId',
        'creditNoteRequestId' => 'creditNoteRequestId',
        'invoiceId' => 'invoiceId',
        'customerId' => 'customerId',
        'type' => 'type',
        'status' => 'status',
        'totalAmount' => 'totalAmount',
        'refundStatus' => 'refundStatus',
        'refundId' => 'refundId',
        'reason' => 'reason',
        'reasonDescription' => 'reasonDescription',
        'refundDestination' => 'refundDestination',
        'effectiveDate' => 'effectiveDate',
        'memo' => 'memo',
        'items' => 'items',
        'issuedAt' => 'issuedAt',
        'refundedAt' => 'refundedAt',
        'voidedAt' => 'voidedAt',
        'createdAt' => 'createdAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'result' => 'setResult',
        'creditNoteId' => 'setCreditNoteId',
        'creditNoteRequestId' => 'setCreditNoteRequestId',
        'invoiceId' => 'setInvoiceId',
        'customerId' => 'setCustomerId',
        'type' => 'setType',
        'status' => 'setStatus',
        'totalAmount' => 'setTotalAmount',
        'refundStatus' => 'setRefundStatus',
        'refundId' => 'setRefundId',
        'reason' => 'setReason',
        'reasonDescription' => 'setReasonDescription',
        'refundDestination' => 'setRefundDestination',
        'effectiveDate' => 'setEffectiveDate',
        'memo' => 'setMemo',
        'items' => 'setItems',
        'issuedAt' => 'setIssuedAt',
        'refundedAt' => 'setRefundedAt',
        'voidedAt' => 'setVoidedAt',
        'createdAt' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'result' => 'getResult',
        'creditNoteId' => 'getCreditNoteId',
        'creditNoteRequestId' => 'getCreditNoteRequestId',
        'invoiceId' => 'getInvoiceId',
        'customerId' => 'getCustomerId',
        'type' => 'getType',
        'status' => 'getStatus',
        'totalAmount' => 'getTotalAmount',
        'refundStatus' => 'getRefundStatus',
        'refundId' => 'getRefundId',
        'reason' => 'getReason',
        'reasonDescription' => 'getReasonDescription',
        'refundDestination' => 'getRefundDestination',
        'effectiveDate' => 'getEffectiveDate',
        'memo' => 'getMemo',
        'items' => 'getItems',
        'issuedAt' => 'getIssuedAt',
        'refundedAt' => 'getRefundedAt',
        'voidedAt' => 'getVoidedAt',
        'createdAt' => 'getCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('result', $data ?? [], null);
        $this->setIfExists('creditNoteId', $data ?? [], null);
        $this->setIfExists('creditNoteRequestId', $data ?? [], null);
        $this->setIfExists('invoiceId', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('totalAmount', $data ?? [], null);
        $this->setIfExists('refundStatus', $data ?? [], null);
        $this->setIfExists('refundId', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('reasonDescription', $data ?? [], null);
        $this->setIfExists('refundDestination', $data ?? [], null);
        $this->setIfExists('effectiveDate', $data ?? [], null);
        $this->setIfExists('memo', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
        $this->setIfExists('issuedAt', $data ?? [], null);
        $this->setIfExists('refundedAt', $data ?? [], null);
        $this->setIfExists('voidedAt', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['result'] === null) {
            $invalidProperties[] = "'result' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets result
     *
     * @return \model\Result
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param \model\Result $result result
     *
     * @return self
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets creditNoteId
     *
     * @return string|null
     */
    public function getCreditNoteId()
    {
        return $this->container['creditNoteId'];
    }

    /**
     * Sets creditNoteId
     *
     * @param string|null $creditNoteId The credit note ID. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setCreditNoteId($creditNoteId)
    {
        $this->container['creditNoteId'] = $creditNoteId;

        return $this;
    }

    /**
     * Gets creditNoteRequestId
     *
     * @return string|null
     */
    public function getCreditNoteRequestId()
    {
        return $this->container['creditNoteRequestId'];
    }

    /**
     * Sets creditNoteRequestId
     *
     * @param string|null $creditNoteRequestId The credit note request id. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setCreditNoteRequestId($creditNoteRequestId)
    {
        $this->container['creditNoteRequestId'] = $creditNoteRequestId;

        return $this;
    }

    /**
     * Gets invoiceId
     *
     * @return string|null
     */
    public function getInvoiceId()
    {
        return $this->container['invoiceId'];
    }

    /**
     * Sets invoiceId
     *
     * @param string|null $invoiceId The invoice ID. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setInvoiceId($invoiceId)
    {
        $this->container['invoiceId'] = $invoiceId;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type The type. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The current status. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets totalAmount
     *
     * @return \model\Amount|null
     */
    public function getTotalAmount()
    {
        return $this->container['totalAmount'];
    }

    /**
     * Sets totalAmount
     *
     * @param \model\Amount|null $totalAmount totalAmount
     *
     * @return self
     */
    public function setTotalAmount($totalAmount)
    {
        $this->container['totalAmount'] = $totalAmount;

        return $this;
    }

    /**
     * Gets refundStatus
     *
     * @return string|null
     */
    public function getRefundStatus()
    {
        return $this->container['refundStatus'];
    }

    /**
     * Sets refundStatus
     *
     * @param string|null $refundStatus The refund status. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setRefundStatus($refundStatus)
    {
        $this->container['refundStatus'] = $refundStatus;

        return $this;
    }

    /**
     * Gets refundId
     *
     * @return string|null
     */
    public function getRefundId()
    {
        return $this->container['refundId'];
    }

    /**
     * Sets refundId
     *
     * @param string|null $refundId The refund id. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setRefundId($refundId)
    {
        $this->container['refundId'] = $refundId;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason The reason for the status change. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setReason($reason)
    {
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets reasonDescription
     *
     * @return string|null
     */
    public function getReasonDescription()
    {
        return $this->container['reasonDescription'];
    }

    /**
     * Sets reasonDescription
     *
     * @param string|null $reasonDescription The detailed description of the reason. Maximum length: 512 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setReasonDescription($reasonDescription)
    {
        $this->container['reasonDescription'] = $reasonDescription;

        return $this;
    }

    /**
     * Gets refundDestination
     *
     * @return string|null
     */
    public function getRefundDestination()
    {
        return $this->container['refundDestination'];
    }

    /**
     * Sets refundDestination
     *
     * @param string|null $refundDestination The refund destination. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setRefundDestination($refundDestination)
    {
        $this->container['refundDestination'] = $refundDestination;

        return $this;
    }

    /**
     * Gets effectiveDate
     *
     * @return string|null
     */
    public function getEffectiveDate()
    {
        return $this->container['effectiveDate'];
    }

    /**
     * Sets effectiveDate
     *
     * @param string|null $effectiveDate The effective date. Maximum length: 29 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setEffectiveDate($effectiveDate)
    {
        $this->container['effectiveDate'] = $effectiveDate;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|null
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|null $memo The memo. Maximum length: 512 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setMemo($memo)
    {
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \model\CreditNoteInquireDetailsItems|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \model\CreditNoteInquireDetailsItems|null $items items
     *
     * @return self
     */
    public function setItems($items)
    {
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets issuedAt
     *
     * @return string|null
     */
    public function getIssuedAt()
    {
        return $this->container['issuedAt'];
    }

    /**
     * Sets issuedAt
     *
     * @param string|null $issuedAt The issued at. Maximum length: 29 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setIssuedAt($issuedAt)
    {
        $this->container['issuedAt'] = $issuedAt;

        return $this;
    }

    /**
     * Gets refundedAt
     *
     * @return string|null
     */
    public function getRefundedAt()
    {
        return $this->container['refundedAt'];
    }

    /**
     * Sets refundedAt
     *
     * @param string|null $refundedAt The refunded at. Maximum length: 29 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setRefundedAt($refundedAt)
    {
        $this->container['refundedAt'] = $refundedAt;

        return $this;
    }

    /**
     * Gets voidedAt
     *
     * @return string|null
     */
    public function getVoidedAt()
    {
        return $this->container['voidedAt'];
    }

    /**
     * Sets voidedAt
     *
     * @param string|null $voidedAt The voided at. Maximum length: 29 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setVoidedAt($voidedAt)
    {
        $this->container['voidedAt'] = $voidedAt;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string|null $createdAt The created at. Maximum length: 29 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
