<?php

/**
 * v1_billing_subscription_create
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Response\billing;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayBillingSubscriptionCreateResponse Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayBillingSubscriptionCreateResponse  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayBillingSubscriptionCreateResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'result' => '\request\model\ResultInfo',
        'subscriptionRequestId' => 'string',
        'subscriptionId' => 'string',
        'customerId' => 'string',
        'invoiceId' => 'string',
        'status' => 'string',
        'currentPeriodStart' => 'string',
        'currentPeriodEnd' => 'string',
        'billingCycleAnchor' => 'string',
        'trialStart' => 'string',
        'trialEnd' => 'string',
        'cancelAt' => 'string',
        'cancelAtPeriodEnd' => 'bool',
        'description' => 'string',
        'collectionMethod' => 'string',
        'daysUntilDue' => 'int',
        'subscriptionItems' => '\request\model\SubscriptionItem[]',
        'discounts' => '\request\model\Discount[]',
        'subscriptionNotifyUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'result' => null,
        'subscriptionRequestId' => null,
        'subscriptionId' => null,
        'customerId' => null,
        'invoiceId' => null,
        'status' => null,
        'currentPeriodStart' => null,
        'currentPeriodEnd' => null,
        'billingCycleAnchor' => null,
        'trialStart' => null,
        'trialEnd' => null,
        'cancelAt' => null,
        'cancelAtPeriodEnd' => null,
        'description' => null,
        'collectionMethod' => null,
        'daysUntilDue' => null,
        'subscriptionItems' => null,
        'discounts' => null,
        'subscriptionNotifyUrl' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'result' => false,
        'subscriptionRequestId' => false,
        'subscriptionId' => false,
        'customerId' => false,
        'invoiceId' => false,
        'status' => false,
        'currentPeriodStart' => false,
        'currentPeriodEnd' => false,
        'billingCycleAnchor' => false,
        'trialStart' => false,
        'trialEnd' => false,
        'cancelAt' => false,
        'cancelAtPeriodEnd' => false,
        'description' => false,
        'collectionMethod' => false,
        'daysUntilDue' => true,
        'subscriptionItems' => false,
        'discounts' => false,
        'subscriptionNotifyUrl' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'result' => 'result',
        'subscriptionRequestId' => 'subscriptionRequestId',
        'subscriptionId' => 'subscriptionId',
        'customerId' => 'customerId',
        'invoiceId' => 'invoiceId',
        'status' => 'status',
        'currentPeriodStart' => 'currentPeriodStart',
        'currentPeriodEnd' => 'currentPeriodEnd',
        'billingCycleAnchor' => 'billingCycleAnchor',
        'trialStart' => 'trialStart',
        'trialEnd' => 'trialEnd',
        'cancelAt' => 'cancelAt',
        'cancelAtPeriodEnd' => 'cancelAtPeriodEnd',
        'description' => 'description',
        'collectionMethod' => 'collectionMethod',
        'daysUntilDue' => 'daysUntilDue',
        'subscriptionItems' => 'subscriptionItems',
        'discounts' => 'discounts',
        'subscriptionNotifyUrl' => 'subscriptionNotifyUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'result' => 'setResult',
        'subscriptionRequestId' => 'setSubscriptionRequestId',
        'subscriptionId' => 'setSubscriptionId',
        'customerId' => 'setCustomerId',
        'invoiceId' => 'setInvoiceId',
        'status' => 'setStatus',
        'currentPeriodStart' => 'setCurrentPeriodStart',
        'currentPeriodEnd' => 'setCurrentPeriodEnd',
        'billingCycleAnchor' => 'setBillingCycleAnchor',
        'trialStart' => 'setTrialStart',
        'trialEnd' => 'setTrialEnd',
        'cancelAt' => 'setCancelAt',
        'cancelAtPeriodEnd' => 'setCancelAtPeriodEnd',
        'description' => 'setDescription',
        'collectionMethod' => 'setCollectionMethod',
        'daysUntilDue' => 'setDaysUntilDue',
        'subscriptionItems' => 'setSubscriptionItems',
        'discounts' => 'setDiscounts',
        'subscriptionNotifyUrl' => 'setSubscriptionNotifyUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'result' => 'getResult',
        'subscriptionRequestId' => 'getSubscriptionRequestId',
        'subscriptionId' => 'getSubscriptionId',
        'customerId' => 'getCustomerId',
        'invoiceId' => 'getInvoiceId',
        'status' => 'getStatus',
        'currentPeriodStart' => 'getCurrentPeriodStart',
        'currentPeriodEnd' => 'getCurrentPeriodEnd',
        'billingCycleAnchor' => 'getBillingCycleAnchor',
        'trialStart' => 'getTrialStart',
        'trialEnd' => 'getTrialEnd',
        'cancelAt' => 'getCancelAt',
        'cancelAtPeriodEnd' => 'getCancelAtPeriodEnd',
        'description' => 'getDescription',
        'collectionMethod' => 'getCollectionMethod',
        'daysUntilDue' => 'getDaysUntilDue',
        'subscriptionItems' => 'getSubscriptionItems',
        'discounts' => 'getDiscounts',
        'subscriptionNotifyUrl' => 'getSubscriptionNotifyUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('result', $data ?? [], null);
        $this->setIfExists('subscriptionRequestId', $data ?? [], null);
        $this->setIfExists('subscriptionId', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('invoiceId', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('currentPeriodStart', $data ?? [], null);
        $this->setIfExists('currentPeriodEnd', $data ?? [], null);
        $this->setIfExists('billingCycleAnchor', $data ?? [], null);
        $this->setIfExists('trialStart', $data ?? [], null);
        $this->setIfExists('trialEnd', $data ?? [], null);
        $this->setIfExists('cancelAt', $data ?? [], null);
        $this->setIfExists('cancelAtPeriodEnd', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('collectionMethod', $data ?? [], null);
        $this->setIfExists('daysUntilDue', $data ?? [], null);
        $this->setIfExists('subscriptionItems', $data ?? [], null);
        $this->setIfExists('discounts', $data ?? [], null);
        $this->setIfExists('subscriptionNotifyUrl', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['result'] === null) {
            $invalidProperties[] = "'result' can't be null";
        }
        if ($this->container['subscriptionRequestId'] === null) {
            $invalidProperties[] = "'subscriptionRequestId' can't be null";
        }
        if ($this->container['subscriptionId'] === null) {
            $invalidProperties[] = "'subscriptionId' can't be null";
        }
        if ($this->container['customerId'] === null) {
            $invalidProperties[] = "'customerId' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['currentPeriodStart'] === null) {
            $invalidProperties[] = "'currentPeriodStart' can't be null";
        }
        if ($this->container['currentPeriodEnd'] === null) {
            $invalidProperties[] = "'currentPeriodEnd' can't be null";
        }
        if ($this->container['collectionMethod'] === null) {
            $invalidProperties[] = "'collectionMethod' can't be null";
        }
        if ($this->container['subscriptionItems'] === null) {
            $invalidProperties[] = "'subscriptionItems' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets result
     *
     * @return \model\ResultInfo
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param \model\ResultInfo $result result
     *
     * @return self
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets subscriptionRequestId
     *
     * @return string
     */
    public function getSubscriptionRequestId()
    {
        return $this->container['subscriptionRequestId'];
    }

    /**
     * Sets subscriptionRequestId
     *
     * @param string $subscriptionRequestId The subscription request id. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setSubscriptionRequestId($subscriptionRequestId)
    {
        $this->container['subscriptionRequestId'] = $subscriptionRequestId;

        return $this;
    }

    /**
     * Gets subscriptionId
     *
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->container['subscriptionId'];
    }

    /**
     * Sets subscriptionId
     *
     * @param string $subscriptionId The subscription ID. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setSubscriptionId($subscriptionId)
    {
        $this->container['subscriptionId'] = $subscriptionId;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string $customerId The unique ID assigned by Antom to identify a customer. Maximum length: 64 characters.
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets invoiceId
     *
     * @return string|null
     */
    public function getInvoiceId()
    {
        return $this->container['invoiceId'];
    }

    /**
     * Sets invoiceId
     *
     * @param string|null $invoiceId The invoice ID. Maximum length: 64 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setInvoiceId($invoiceId)
    {
        $this->container['invoiceId'] = $invoiceId;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The current status. Maximum length: 20 characters.
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets currentPeriodStart
     *
     * @return string
     */
    public function getCurrentPeriodStart()
    {
        return $this->container['currentPeriodStart'];
    }

    /**
     * Sets currentPeriodStart
     *
     * @param string $currentPeriodStart The current period start.
     *
     * @return self
     */
    public function setCurrentPeriodStart($currentPeriodStart)
    {
        $this->container['currentPeriodStart'] = $currentPeriodStart;

        return $this;
    }

    /**
     * Gets currentPeriodEnd
     *
     * @return string
     */
    public function getCurrentPeriodEnd()
    {
        return $this->container['currentPeriodEnd'];
    }

    /**
     * Sets currentPeriodEnd
     *
     * @param string $currentPeriodEnd The current period end.
     *
     * @return self
     */
    public function setCurrentPeriodEnd($currentPeriodEnd)
    {
        $this->container['currentPeriodEnd'] = $currentPeriodEnd;

        return $this;
    }

    /**
     * Gets billingCycleAnchor
     *
     * @return string|null
     */
    public function getBillingCycleAnchor()
    {
        return $this->container['billingCycleAnchor'];
    }

    /**
     * Sets billingCycleAnchor
     *
     * @param string|null $billingCycleAnchor The billing cycle anchor. Note: See documentation for details.
     *
     * @return self
     */
    public function setBillingCycleAnchor($billingCycleAnchor)
    {
        $this->container['billingCycleAnchor'] = $billingCycleAnchor;

        return $this;
    }

    /**
     * Gets trialStart
     *
     * @return string|null
     */
    public function getTrialStart()
    {
        return $this->container['trialStart'];
    }

    /**
     * Sets trialStart
     *
     * @param string|null $trialStart The trial start. Maximum length: 32 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setTrialStart($trialStart)
    {
        $this->container['trialStart'] = $trialStart;

        return $this;
    }

    /**
     * Gets trialEnd
     *
     * @return string|null
     */
    public function getTrialEnd()
    {
        return $this->container['trialEnd'];
    }

    /**
     * Sets trialEnd
     *
     * @param string|null $trialEnd The trial end. Note: See documentation for details.
     *
     * @return self
     */
    public function setTrialEnd($trialEnd)
    {
        $this->container['trialEnd'] = $trialEnd;

        return $this;
    }

    /**
     * Gets cancelAt
     *
     * @return string|null
     */
    public function getCancelAt()
    {
        return $this->container['cancelAt'];
    }

    /**
     * Sets cancelAt
     *
     * @param string|null $cancelAt The cancel at. Note: See documentation for details.
     *
     * @return self
     */
    public function setCancelAt($cancelAt)
    {
        $this->container['cancelAt'] = $cancelAt;

        return $this;
    }

    /**
     * Gets cancelAtPeriodEnd
     *
     * @return bool|null
     */
    public function getCancelAtPeriodEnd()
    {
        return $this->container['cancelAtPeriodEnd'];
    }

    /**
     * Sets cancelAtPeriodEnd
     *
     * @param bool|null $cancelAtPeriodEnd The cancel at period end. Note: See documentation for details.
     *
     * @return self
     */
    public function setCancelAtPeriodEnd($cancelAtPeriodEnd)
    {
        $this->container['cancelAtPeriodEnd'] = $cancelAtPeriodEnd;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description. Maximum length: 500 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets collectionMethod
     *
     * @return string
     */
    public function getCollectionMethod()
    {
        return $this->container['collectionMethod'];
    }

    /**
     * Sets collectionMethod
     *
     * @param string $collectionMethod The collection method.
     *
     * @return self
     */
    public function setCollectionMethod($collectionMethod)
    {
        $this->container['collectionMethod'] = $collectionMethod;

        return $this;
    }

    /**
     * Gets daysUntilDue
     *
     * @return int|null
     */
    public function getDaysUntilDue()
    {
        return $this->container['daysUntilDue'];
    }

    /**
     * Sets daysUntilDue
     *
     * @param int|null $daysUntilDue The days until due. Note: See documentation for details.
     *
     * @return self
     */
    public function setDaysUntilDue($daysUntilDue)
    {
        $this->container['daysUntilDue'] = $daysUntilDue;

        return $this;
    }

    /**
     * Gets subscriptionItems
     *
     * @return \model\SubscriptionItem[]
     */
    public function getSubscriptionItems()
    {
        return $this->container['subscriptionItems'];
    }

    /**
     * Sets subscriptionItems
     *
     * @param \model\SubscriptionItem[] $subscriptionItems The subscription items.
     *
     * @return self
     */
    public function setSubscriptionItems($subscriptionItems)
    {
        $this->container['subscriptionItems'] = $subscriptionItems;

        return $this;
    }

    /**
     * Gets discounts
     *
     * @return \model\Discount[]|null
     */
    public function getDiscounts()
    {
        return $this->container['discounts'];
    }

    /**
     * Sets discounts
     *
     * @param \model\Discount[]|null $discounts The discounts applied. Note: See documentation for details.
     *
     * @return self
     */
    public function setDiscounts($discounts)
    {
        $this->container['discounts'] = $discounts;

        return $this;
    }

    /**
     * Gets subscriptionNotifyUrl
     *
     * @return string|null
     */
    public function getSubscriptionNotifyUrl()
    {
        return $this->container['subscriptionNotifyUrl'];
    }

    /**
     * Sets subscriptionNotifyUrl
     *
     * @param string|null $subscriptionNotifyUrl The subscription notify url. Maximum length: 512 characters. Note: See documentation for details.
     *
     * @return self
     */
    public function setSubscriptionNotifyUrl($subscriptionNotifyUrl)
    {
        $this->container['subscriptionNotifyUrl'] = $subscriptionNotifyUrl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
