<?php

/**
 * /v1/aba/funds/inquireExchange
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Response\aba;

use \ArrayAccess;
use Request\AlipayRequest;
use Model\ModelInterface;
use Model\ObjectSerializer;

/**
 * AlipayInquireExchangeResponse Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayInquireExchangeResponse  implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayInquireExchangeResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'result' => '\request\model\Result',
        'exchangeResult' => '\request\model\Result',
        'exchangeTradeType' => 'string',
        'exchangeMode' => 'string',
        'exchangeRequestId' => 'string',
        'quote' => '\request\model\Quote',
        'sellAmount' => '\request\model\Amount',
        'buyAmount' => '\request\model\Amount',
        'exchangeId' => 'string',
        'exchangeStartTime' => 'string',
        'exchangeEndTime' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'result' => null,
        'exchangeResult' => null,
        'exchangeTradeType' => null,
        'exchangeMode' => null,
        'exchangeRequestId' => null,
        'quote' => null,
        'sellAmount' => null,
        'buyAmount' => null,
        'exchangeId' => null,
        'exchangeStartTime' => null,
        'exchangeEndTime' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'result' => false,
        'exchangeResult' => false,
        'exchangeTradeType' => false,
        'exchangeMode' => false,
        'exchangeRequestId' => false,
        'quote' => false,
        'sellAmount' => false,
        'buyAmount' => false,
        'exchangeId' => false,
        'exchangeStartTime' => false,
        'exchangeEndTime' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'result' => 'result',
        'exchangeResult' => 'exchangeResult',
        'exchangeTradeType' => 'exchangeTradeType',
        'exchangeMode' => 'exchangeMode',
        'exchangeRequestId' => 'exchangeRequestId',
        'quote' => 'quote',
        'sellAmount' => 'sellAmount',
        'buyAmount' => 'buyAmount',
        'exchangeId' => 'exchangeId',
        'exchangeStartTime' => 'exchangeStartTime',
        'exchangeEndTime' => 'exchangeEndTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'result' => 'setResult',
        'exchangeResult' => 'setExchangeResult',
        'exchangeTradeType' => 'setExchangeTradeType',
        'exchangeMode' => 'setExchangeMode',
        'exchangeRequestId' => 'setExchangeRequestId',
        'quote' => 'setQuote',
        'sellAmount' => 'setSellAmount',
        'buyAmount' => 'setBuyAmount',
        'exchangeId' => 'setExchangeId',
        'exchangeStartTime' => 'setExchangeStartTime',
        'exchangeEndTime' => 'setExchangeEndTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'result' => 'getResult',
        'exchangeResult' => 'getExchangeResult',
        'exchangeTradeType' => 'getExchangeTradeType',
        'exchangeMode' => 'getExchangeMode',
        'exchangeRequestId' => 'getExchangeRequestId',
        'quote' => 'getQuote',
        'sellAmount' => 'getSellAmount',
        'buyAmount' => 'getBuyAmount',
        'exchangeId' => 'getExchangeId',
        'exchangeStartTime' => 'getExchangeStartTime',
        'exchangeEndTime' => 'getExchangeEndTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('result', $data ?? [], null);
        $this->setIfExists('exchangeResult', $data ?? [], null);
        $this->setIfExists('exchangeTradeType', $data ?? [], null);
        $this->setIfExists('exchangeMode', $data ?? [], null);
        $this->setIfExists('exchangeRequestId', $data ?? [], null);
        $this->setIfExists('quote', $data ?? [], null);
        $this->setIfExists('sellAmount', $data ?? [], null);
        $this->setIfExists('buyAmount', $data ?? [], null);
        $this->setIfExists('exchangeId', $data ?? [], null);
        $this->setIfExists('exchangeStartTime', $data ?? [], null);
        $this->setIfExists('exchangeEndTime', $data ?? [], null);

            }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets result
     *
     * @return \model\Result|null
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param \model\Result|null $result result
     *
     * @return self
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets exchangeResult
     *
     * @return \model\Result|null
     */
    public function getExchangeResult()
    {
        return $this->container['exchangeResult'];
    }

    /**
     * Sets exchangeResult
     *
     * @param \model\Result|null $exchangeResult exchangeResult
     *
     * @return self
     */
    public function setExchangeResult($exchangeResult)
    {
        $this->container['exchangeResult'] = $exchangeResult;

        return $this;
    }

    /**
     * Gets exchangeTradeType
     *
     * @return string|null
     */
    public function getExchangeTradeType()
    {
        return $this->container['exchangeTradeType'];
    }

    /**
     * Sets exchangeTradeType
     *
     * @param string|null $exchangeTradeType Foreign exchange delivery type. Possible value range:   SPOT: Real-time exchange rate.
     *
     * @return self
     */
    public function setExchangeTradeType($exchangeTradeType)
    {
        $this->container['exchangeTradeType'] = $exchangeTradeType;

        return $this;
    }

    /**
     * Gets exchangeMode
     *
     * @return string|null
     */
    public function getExchangeMode()
    {
        return $this->container['exchangeMode'];
    }

    /**
     * Sets exchangeMode
     *
     * @param string|null $exchangeMode Foreign exchange delivery model. Possible value range:   APPOINTED: indicates an exchange rate at the appointed time.
     *
     * @return self
     */
    public function setExchangeMode($exchangeMode)
    {
        $this->container['exchangeMode'] = $exchangeMode;

        return $this;
    }

    /**
     * Gets exchangeRequestId
     *
     * @return string|null
     */
    public function getExchangeRequestId()
    {
        return $this->container['exchangeRequestId'];
    }

    /**
     * Sets exchangeRequestId
     *
     * @param string|null $exchangeRequestId exchangeRequestId
     *
     * @return self
     */
    public function setExchangeRequestId($exchangeRequestId)
    {
        $this->container['exchangeRequestId'] = $exchangeRequestId;

        return $this;
    }

    /**
     * Gets quote
     *
     * @return \model\Quote|null
     */
    public function getQuote()
    {
        return $this->container['quote'];
    }

    /**
     * Sets quote
     *
     * @param \model\Quote|null $quote quote
     *
     * @return self
     */
    public function setQuote($quote)
    {
        $this->container['quote'] = $quote;

        return $this;
    }

    /**
     * Gets sellAmount
     *
     * @return \model\Amount|null
     */
    public function getSellAmount()
    {
        return $this->container['sellAmount'];
    }

    /**
     * Sets sellAmount
     *
     * @param \model\Amount|null $sellAmount sellAmount
     *
     * @return self
     */
    public function setSellAmount($sellAmount)
    {
        $this->container['sellAmount'] = $sellAmount;

        return $this;
    }

    /**
     * Gets buyAmount
     *
     * @return \model\Amount|null
     */
    public function getBuyAmount()
    {
        return $this->container['buyAmount'];
    }

    /**
     * Sets buyAmount
     *
     * @param \model\Amount|null $buyAmount buyAmount
     *
     * @return self
     */
    public function setBuyAmount($buyAmount)
    {
        $this->container['buyAmount'] = $buyAmount;

        return $this;
    }

    /**
     * Gets exchangeId
     *
     * @return string|null
     */
    public function getExchangeId()
    {
        return $this->container['exchangeId'];
    }

    /**
     * Sets exchangeId
     *
     * @param string|null $exchangeId exchangeId
     *
     * @return self
     */
    public function setExchangeId($exchangeId)
    {
        $this->container['exchangeId'] = $exchangeId;

        return $this;
    }

    /**
     * Gets exchangeStartTime
     *
     * @return string|null
     */
    public function getExchangeStartTime()
    {
        return $this->container['exchangeStartTime'];
    }

    /**
     * Sets exchangeStartTime
     *
     * @param string|null $exchangeStartTime exchangeStartTime
     *
     * @return self
     */
    public function setExchangeStartTime($exchangeStartTime)
    {
        $this->container['exchangeStartTime'] = $exchangeStartTime;

        return $this;
    }

    /**
     * Gets exchangeEndTime
     *
     * @return string|null
     */
    public function getExchangeEndTime()
    {
        return $this->container['exchangeEndTime'];
    }

    /**
     * Sets exchangeEndTime
     *
     * @param string|null $exchangeEndTime exchangeEndTime
     *
     * @return self
     */
    public function setExchangeEndTime($exchangeEndTime)
    {
        $this->container['exchangeEndTime'] = $exchangeEndTime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
